

-- <ChangeSet id="load seed data" delimiter=";" />
  
  INSERT INTO BILLING.USERS (USERID, USERNAME) VALUES (1, 'Aiden');
  INSERT INTO BILLING.USERS (USERID, USERNAME) VALUES (2, 'Ethan, Allen');
  INSERT INTO BILLING.USERS (USERID, USERNAME) VALUES (3, 'Liam');
  INSERT INTO BILLING.USERS (USERID, USERNAME) VALUES (4, 'Noah');
  INSERT INTO BILLING.USERS (USERID, USERNAME) VALUES (5, 'Jacob');
  INSERT INTO BILLING.USERS (USERID, USERNAME) VALUES (6, 'Benjamin');
  INSERT INTO BILLING.USERS (USERID, USERNAME) VALUES (7, 'qamatic');
