image: maven:latest

stages:
  - install
  - test
  - run

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/


install:
  stage: install
  script:
    - mvn initialize -P install-drivers
