-- <ChangeSet id="create schema" delimiter=";" />

  DROP SCHEMA IF EXISTS BILLING;
  CREATE SCHEMA IF NOT EXISTS BILLING;
  
  CREATE TABLE IF NOT EXISTS BILLING.USERS
  (
    USERID      INT NOT NULL,
    USERNAME    VARCHAR2(50),
    RATE        NUMBER(12, 2),
    CREATE_TIME DATE DEFAULT sysdate,
    CONSTRAINT PK_USERID PRIMARY KEY (USERID)
  );
