# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
executorType: machine
jobs:
  build:
    docker:
    machine:
      image: ubuntu-1604:201903-01    # pins image to specific version

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      POSTGRES_DB_ADMIN_USERNAME: root
      POSTGRES_DB_ADMIN_PASSWORD: password
      POSTGRES_DB_URL: jdbc:postgresql://localhost:5432/

    steps:
      - checkout
      - run: ./startlocaldb.sh

     # run tests!
      - run: mvn initialize -P install-drivers
      - run: mvn clean test




