
version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails

    docker:

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test


    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn initialize -P install-drivers
      - run: mvn clean test
