-- <ChangeSet id="create schema" delimiter=";" />
DROP SCHEMA IF EXISTS BINARY_IMPDB;
CREATE SCHEMA IF NOT EXISTS BINARY_IMPDB;

CREATE TABLE IF NOT EXISTS BINARY_IMPDB.CITIES
(
  ID      INT NOT NULL,
  CITY    VARCHAR2(50),
  STATE   VARCHAR2(50),
  COUNTRY VARCHAR2(50),
  CONSTRAINT PK_ID PRIMARY KEY (ID)
);


