-- <ChangeSet id="single script" delimiter=";" />

DROP ALL OBJECTS;

CREATE SCHEMA IF NOT EXISTS HRDB;

CREATE TABLE IF NOT EXISTS HRDB.USERS
(USERID INT NOT NULL , USERNAME VARCHAR2(50),  RATE NUMBER(12,2), CREATE_TIME DATE DEFAULT sysdate, CONSTRAINT PK_USERID PRIMARY KEY (USERID ));

